// app/terms-and-conditions/page.tsx
import { SITE_URL } from "@/lib/constants"

export const metadata = {
    title: "Terms and Conditions | JSON Forge",
    description: "Read the Terms and Conditions of using JSON Forge online tools.",
    keywords: [
        "Terms and Conditions",
        "JSON Forge Terms",
        "Website Usage Policy",
        "User Agreement",
        "Disclaimer JSON Forge",
        "Liability Terms",
        "Online Tool Terms"
    ],
    alternates: {
        canonical: "/terms-and-conditions",
    },
    openGraph: {
        title: "Terms and Conditions | JSON Forge",
        description: "Read the Terms and Conditions of using JSON Forge online tools.",
        url: `${SITE_URL}/terms-and-conditions`,
        siteName: "JSON Forge",
        type: "website"
    },
};
  
export default function TermsAndConditions() {
    return (
      <div className="flex items-center justify-center min-h-screen p-6">
        <div className="max-w-3xl w-full">
          <h1 className="text-3xl font-bold text-center mb-6">Terms and Conditions</h1>
  
          <p className="mb-4">
            By accessing and using JSON Forge, you accept and agree to be bound by the terms and provision of this agreement.
          </p>
  
          <h2 className="text-2xl font-semibold mb-2">Use of the Website</h2>
          <p className="mb-4">
            JSON Forge provides free tools for working with JSON and related formats. You agree to use the website only for lawful purposes.
          </p>
  
          <h2 className="text-2xl font-semibold mb-2">Disclaimer</h2>
          <p className="mb-4">
            The tools and content provided are &quot;as is&quot; without warranties of any kind. We do not guarantee the accuracy, completeness, or reliability of the results generated by our tools.
          </p>
  
          <h2 className="text-2xl font-semibold mb-2">Limitation of Liability</h2>
          <p className="mb-4">
            JSON Forge shall not be held liable for any direct, indirect, incidental, consequential, or punitive damages arising out of your access to or use of the website.
          </p>
  
          <h2 className="text-2xl font-semibold mb-2">Changes to Terms</h2>
          <p className="mb-4">
            We reserve the right to update or modify these terms at any time without prior notice. Changes will be effective immediately upon posting.
          </p>
  
          <h2 className="text-2xl font-semibold mb-2">Contact Us</h2>
          <p className="mb-4">
            For any questions about these Terms and Conditions, please contact us through the <a href="/contact-us" className="text-blue-600 underline">Contact Us</a> page.
          </p>
        </div>
      </div>
    );
}
  